feat(NSP-1): update script pre-commit

diff --git a/scripts/git-hooks/pre-commit b/scripts/git-hooks/pre-commit
--- a/scripts/git-hooks/pre-commit
+++ b/scripts/git-hooks/pre-commit
@@ -5,9 +5,8 @@ echo "Running unit tests before commit..."
 status=$?
 
 if [ $status -ne 0 ]; then
-  echo "Unit tests failed. Aborting commit."
+  echo "Unit tests failed. Aborting commit." >&2
   exit 1
 fi
 
 echo "Unit tests passed."
-exit 0
